FROM --platform=$BUILDPLATFORM node:26-bookworm AS client-builder
WORKDIR /app/client
COPY client/package*.json ./
RUN npm config set fetch-retries 10 \
    && npm config set fetch-retry-mintimeout 100000 \
    && npm config set fetch-retry-maxtimeout 600000
RUN npm ci --loglevel=info
COPY client/ ./
COPY api.d.ts ../api.d.ts
RUN npm run build --loglevel=info

FROM node:26-bookworm AS server-builder
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app
COPY package*.json ./
ENV DOCKER="YES"
RUN npm config set fetch-retries 10 \
    && npm config set fetch-retry-mintimeout 100000 \
    && npm config set fetch-retry-maxtimeout 600000
RUN npm ci --loglevel=info
COPY tsconfig.json ./
COPY api.d.ts ./
COPY api.yml ./
COPY src/ ./src/
RUN npx tsc
RUN npm prune --omit=dev

FROM node:26-bookworm-slim
LABEL maintainer="knzfujii"
WORKDIR /app
COPY --from=server-builder /app/package.json ./
COPY --from=server-builder /app/node_modules ./node_modules
COPY --from=server-builder /app/dist ./dist
COPY config/ ./config/
COPY api.yml ./
COPY --from=client-builder /app/client/dist ./client/dist
RUN mkdir -p /app/data /app/logs /app/thumbnail /app/recorded
EXPOSE 8888
CMD ["node", "dist/index.js"]
