FROM --platform=$BUILDPLATFORM node:26-alpine AS client-builder
WORKDIR /app/client
COPY client/package*.json ./
RUN npm config set fetch-retries 10 \
    && npm config set fetch-retry-mintimeout 100000 \
    && npm config set fetch-retry-maxtimeout 600000
RUN npm install --no-save --loglevel=info
COPY client/ ./
COPY api.d.ts ../api.d.ts
RUN npm run build --loglevel=info

FROM node:26-alpine AS server-builder
WORKDIR /app
COPY package*.json ./
ENV DOCKER="YES"
RUN npm config set fetch-retries 10 \
    && npm config set fetch-retry-mintimeout 100000 \
    && npm config set fetch-retry-maxtimeout 600000
RUN npm install --no-save --loglevel=info
COPY . .
RUN rm -rf client
RUN npm run build-server --loglevel=info
RUN npm prune --production

FROM node:26-alpine
LABEL maintainer="knzfujii"
WORKDIR /app
COPY --from=server-builder /app/package.json ./
COPY --from=server-builder /app/node_modules ./node_modules
COPY --from=server-builder /app/dist ./dist
COPY --from=server-builder /app/config ./config
COPY --from=server-builder /app/api.yml ./
COPY --from=client-builder /app/client/dist ./client/dist
EXPOSE 8888
ENTRYPOINT ["npm"]
CMD ["start"]

