import { bigint, boolean, int, mysqlTable, text, varchar } from 'drizzle-orm/mysql-core';

export const programs = mysqlTable('program', {
    id: bigint('id', { mode: 'number' }).primaryKey(),
    updateTime: bigint('updateTime', { mode: 'number' }).notNull(),
    channelId: bigint('channelId', { mode: 'number' }).notNull(),
    eventId: bigint('eventId', { mode: 'number' }).notNull(),
    serviceId: int('serviceId').notNull(),
    networkId: int('networkId').notNull(),
    startAt: bigint('startAt', { mode: 'number' }).notNull(),
    endAt: bigint('endAt', { mode: 'number' }).notNull(),
    startHour: int('startHour').notNull(),
    week: int('week').notNull(),
    duration: int('duration').notNull(),
    isFree: boolean('isFree').notNull(),
    name: text('name').notNull(),
    halfWidthName: text('halfWidthName').notNull(),
    shortName: text('shortName').notNull(),
    description: text('description'),
    halfWidthDescription: text('halfWidthDescription'),
    extended: text('extended'),
    halfWidthExtended: text('halfWidthExtended'),
    rawExtended: text('rawExtended'),
    rawHalfWidthExtended: text('rawHalfWidthExtended'),
    genre1: int('genre1'),
    subGenre1: int('subGenre1'),
    genre2: int('genre2'),
    subGenre2: int('subGenre2'),
    genre3: int('genre3'),
    subGenre3: int('subGenre3'),
    channelType: varchar('channelType', { length: 255 }).notNull(),
    channel: varchar('channel', { length: 255 }).notNull(),
    videoType: text('videoType'),
    videoResolution: text('videoResolution'),
    videoStreamContent: int('videoStreamContent'),
    videoComponentType: int('videoComponentType'),
    audioSamplingRate: int('audioSamplingRate'),
    audioComponentType: int('audioComponentType'),
});

export type ProgramSelect = typeof programs.$inferSelect;
export type ProgramInsert = typeof programs.$inferInsert;
