import { bigint, boolean, index, int, mysqlTable, text } from 'drizzle-orm/mysql-core';

export const reserves = mysqlTable(
    'reserve',
    {
        id: int('id').autoincrement().primaryKey(),
        updateTime: bigint('updateTime', { mode: 'number' }).notNull(),
        ruleId: int('ruleId'),
        ruleUpdateCnt: int('ruleUpdateCnt'),
        isSkip: boolean('isSkip').notNull().default(false),
        isConflict: boolean('isConflict').notNull().default(false),
        allowEndLack: boolean('allowEndLack').notNull().default(false),
        tags: text('tags'),
        isOverlap: boolean('isOverlap').notNull().default(false),
        isIgnoreOverlap: boolean('isIgnoreOverlap').notNull().default(false),
        isTimeSpecified: boolean('isTimeSpecified').notNull().default(false),
        isEventRelay: boolean('isEventRelay').notNull().default(false),
        parentDirectoryName: text('parentDirectoryName'),
        directory: text('directory'),
        recordedFormat: text('recordedFormat'),
        encodeMode1: text('encodeMode1'),
        encodeParentDirectoryName1: text('encodeParentDirectoryName1'),
        encodeDirectory1: text('encodeDirectory1'),
        encodeMode2: text('encodeMode2'),
        encodeParentDirectoryName2: text('encodeParentDirectoryName2'),
        encodeDirectory2: text('encodeDirectory2'),
        encodeMode3: text('encodeMode3'),
        encodeParentDirectoryName3: text('encodeParentDirectoryName3'),
        encodeDirectory3: text('encodeDirectory3'),
        isDeleteOriginalAfterEncode: boolean('isDeleteOriginalAfterEncode').notNull().default(false),
        programId: bigint('programId', { mode: 'number' }),
        programUpdateTime: bigint('programUpdateTime', { mode: 'number' }),
        channelId: bigint('channelId', { mode: 'number' }).notNull(),
        channel: text('channel').notNull(),
        channelType: text('channelType').notNull(),
        startAt: bigint('startAt', { mode: 'number' }).notNull(),
        endAt: bigint('endAt', { mode: 'number' }).notNull(),
        name: text('name'),
        halfWidthName: text('halfWidthName'),
        shortName: text('shortName'),
        description: text('description'),
        halfWidthDescription: text('halfWidthDescription'),
        extended: text('extended'),
        halfWidthExtended: text('halfWidthExtended'),
        rawExtended: text('rawExtended'),
        rawHalfWidthExtended: text('rawHalfWidthExtended'),
        genre1: int('genre1'),
        subGenre1: int('subGenre1'),
        genre2: int('genre2'),
        subGenre2: int('subGenre2'),
        genre3: int('genre3'),
        subGenre3: int('subGenre3'),
        videoType: text('videoType'),
        videoResolution: text('videoResolution'),
        videoStreamContent: int('videoStreamContent'),
        videoComponentType: int('videoComponentType'),
        audioSamplingRate: int('audioSamplingRate'),
        audioComponentType: int('audioComponentType'),
    },
    table => [
        index('idx_reserve_start_end').on(table.startAt, table.endAt),
        index('idx_reserve_rule').on(table.ruleId),
        index('idx_reserve_channel_start').on(table.channelId, table.startAt),
    ],
);

export type ReserveSelect = typeof reserves.$inferSelect;
export type ReserveInsert = typeof reserves.$inferInsert;
