import { boolean, int, mysqlTable, text } from 'drizzle-orm/mysql-core';

export const rules = mysqlTable('rule', {
    id: int('id').autoincrement().primaryKey(),
    updateCnt: int('updateCnt').notNull().default(0),
    isTimeSpecification: boolean('isTimeSpecification').notNull().default(false),
    keyword: text('keyword'),
    halfWidthKeyword: text('halfWidthKeyword'),
    ignoreKeyword: text('ignoreKeyword'),
    halfWidthIgnoreKeyword: text('halfWidthIgnoreKeyword'),
    keyCS: boolean('keyCS').notNull().default(false),
    keyRegExp: boolean('keyRegExp').notNull().default(false),
    name: boolean('name').notNull().default(false),
    description: boolean('description').notNull().default(false),
    extended: boolean('extended').notNull().default(false),
    ignoreKeyCS: boolean('ignoreKeyCS').notNull().default(false),
    ignoreKeyRegExp: boolean('ignoreKeyRegExp').notNull().default(false),
    ignoreName: boolean('ignoreName').notNull().default(false),
    ignoreDescription: boolean('ignoreDescription').notNull().default(false),
    ignoreExtended: boolean('ignoreExtended').notNull().default(false),
    GR: boolean('GR').notNull().default(false),
    BS: boolean('BS').notNull().default(false),
    CS: boolean('CS').notNull().default(false),
    SKY: boolean('SKY').notNull().default(false),
    channelIds: text('channelIds'),
    genres: text('genres'),
    times: text('times'),
    isFree: boolean('isFree').notNull().default(false),
    durationMin: int('durationMin'),
    durationMax: int('durationMax'),
    searchPeriods: text('searchPeriods'),
    enable: boolean('enable').notNull().default(false),
    avoidDuplicate: boolean('avoidDuplicate').notNull().default(false),
    periodToAvoidDuplicate: int('periodToAvoidDuplicate'),
    allowEndLack: boolean('allowEndLack').notNull().default(true),
    tags: text('tags'),
    parentDirectoryName: text('parentDirectoryName'),
    directory: text('directory'),
    recordedFormat: text('recordedFormat'),
    mode1: text('mode1'),
    parentDirectoryName1: text('parentDirectoryName1'),
    directory1: text('directory1'),
    mode2: text('mode2'),
    parentDirectoryName2: text('parentDirectoryName2'),
    directory2: text('directory2'),
    mode3: text('mode3'),
    parentDirectoryName3: text('parentDirectoryName3'),
    directory3: text('directory3'),
    isDeleteOriginalAfterEncode: boolean('isDeleteOriginalAfterEncode').notNull().default(false),
});

export type RuleSelect = typeof rules.$inferSelect;
export type RuleInsert = typeof rules.$inferInsert;
