import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const reserves = sqliteTable('reserve', {
    id: integer('id', { mode: 'number' }).primaryKey({ autoIncrement: true }),
    updateTime: integer('updateTime', { mode: 'number' }).notNull(),
    ruleId: integer('ruleId'),
    ruleUpdateCnt: integer('ruleUpdateCnt'),
    isSkip: integer('isSkip', { mode: 'boolean' }).notNull().default(false),
    isConflict: integer('isConflict', { mode: 'boolean' }).notNull().default(false),
    allowEndLack: integer('allowEndLack', { mode: 'boolean' }).notNull().default(false),
    tags: text('tags'),
    isOverlap: integer('isOverlap', { mode: 'boolean' }).notNull().default(false),
    isIgnoreOverlap: integer('isIgnoreOverlap', { mode: 'boolean' }).notNull().default(false),
    isTimeSpecified: integer('isTimeSpecified', { mode: 'boolean' }).notNull().default(false),
    isEventRelay: integer('isEventRelay', { mode: 'boolean' }).notNull().default(false),
    parentDirectoryName: text('parentDirectoryName'),
    directory: text('directory'),
    recordedFormat: text('recordedFormat'),
    encodeMode1: text('encodeMode1'),
    encodeParentDirectoryName1: text('encodeParentDirectoryName1'),
    encodeDirectory1: text('encodeDirectory1'),
    encodeMode2: text('encodeMode2'),
    encodeParentDirectoryName2: text('encodeParentDirectoryName2'),
    encodeDirectory2: text('encodeDirectory2'),
    encodeMode3: text('encodeMode3'),
    encodeParentDirectoryName3: text('encodeParentDirectoryName3'),
    encodeDirectory3: text('encodeDirectory3'),
    isDeleteOriginalAfterEncode: integer('isDeleteOriginalAfterEncode', { mode: 'boolean' }).notNull().default(false),
    programId: integer('programId', { mode: 'number' }),
    programUpdateTime: integer('programUpdateTime', { mode: 'number' }),
    channelId: integer('channelId', { mode: 'number' }).notNull(),
    channel: text('channel').notNull(),
    channelType: text('channelType').notNull(),
    startAt: integer('startAt', { mode: 'number' }).notNull(),
    endAt: integer('endAt', { mode: 'number' }).notNull(),
    name: text('name'),
    halfWidthName: text('halfWidthName'),
    shortName: text('shortName'),
    description: text('description'),
    halfWidthDescription: text('halfWidthDescription'),
    extended: text('extended'),
    halfWidthExtended: text('halfWidthExtended'),
    rawExtended: text('rawExtended'),
    rawHalfWidthExtended: text('rawHalfWidthExtended'),
    genre1: integer('genre1'),
    subGenre1: integer('subGenre1'),
    genre2: integer('genre2'),
    subGenre2: integer('subGenre2'),
    genre3: integer('genre3'),
    subGenre3: integer('subGenre3'),
    videoType: text('videoType'),
    videoResolution: text('videoResolution'),
    videoStreamContent: integer('videoStreamContent'),
    videoComponentType: integer('videoComponentType'),
    audioSamplingRate: integer('audioSamplingRate'),
    audioComponentType: integer('audioComponentType'),
});

export type ReserveSelect = typeof reserves.$inferSelect;
export type ReserveInsert = typeof reserves.$inferInsert;
