import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const rules = sqliteTable('rule', {
    id: integer('id', { mode: 'number' }).primaryKey({ autoIncrement: true }),
    updateCnt: integer('updateCnt').notNull().default(0),
    isTimeSpecification: integer('isTimeSpecification', { mode: 'boolean' }).notNull().default(false),
    keyword: text('keyword'),
    halfWidthKeyword: text('halfWidthKeyword'),
    ignoreKeyword: text('ignoreKeyword'),
    halfWidthIgnoreKeyword: text('halfWidthIgnoreKeyword'),
    keyCS: integer('keyCS', { mode: 'boolean' }).notNull().default(false),
    keyRegExp: integer('keyRegExp', { mode: 'boolean' }).notNull().default(false),
    name: integer('name', { mode: 'boolean' }).notNull().default(false),
    description: integer('description', { mode: 'boolean' }).notNull().default(false),
    extended: integer('extended', { mode: 'boolean' }).notNull().default(false),
    ignoreKeyCS: integer('ignoreKeyCS', { mode: 'boolean' }).notNull().default(false),
    ignoreKeyRegExp: integer('ignoreKeyRegExp', { mode: 'boolean' }).notNull().default(false),
    ignoreName: integer('ignoreName', { mode: 'boolean' }).notNull().default(false),
    ignoreDescription: integer('ignoreDescription', { mode: 'boolean' }).notNull().default(false),
    ignoreExtended: integer('ignoreExtended', { mode: 'boolean' }).notNull().default(false),
    GR: integer('GR', { mode: 'boolean' }).notNull().default(false),
    BS: integer('BS', { mode: 'boolean' }).notNull().default(false),
    CS: integer('CS', { mode: 'boolean' }).notNull().default(false),
    SKY: integer('SKY', { mode: 'boolean' }).notNull().default(false),
    channelIds: text('channelIds'),
    genres: text('genres'),
    times: text('times'),
    isFree: integer('isFree', { mode: 'boolean' }).notNull().default(false),
    durationMin: integer('durationMin'),
    durationMax: integer('durationMax'),
    searchPeriods: text('searchPeriods'),
    enable: integer('enable', { mode: 'boolean' }).notNull().default(false),
    avoidDuplicate: integer('avoidDuplicate', { mode: 'boolean' }).notNull().default(false),
    periodToAvoidDuplicate: integer('periodToAvoidDuplicate'),
    allowEndLack: integer('allowEndLack', { mode: 'boolean' }).notNull().default(false),
    tags: text('tags'),
    parentDirectoryName: text('parentDirectoryName'),
    directory: text('directory'),
    recordedFormat: text('recordedFormat'),
    mode1: text('mode1'),
    parentDirectoryName1: text('parentDirectoryName1'),
    directory1: text('directory1'),
    mode2: text('mode2'),
    parentDirectoryName2: text('parentDirectoryName2'),
    directory2: text('directory2'),
    mode3: text('mode3'),
    parentDirectoryName3: text('parentDirectoryName3'),
    directory3: text('directory3'),
    isDeleteOriginalAfterEncode: integer('isDeleteOriginalAfterEncode', { mode: 'boolean' }).notNull().default(false),
});

export type RuleSelect = typeof rules.$inferSelect;
export type RuleInsert = typeof rules.$inferInsert;
